### ISSUE TITLE
All pedestrian disappeared when press "start combine recording" in dataset mod

### ISSUE THREAD

**Issue by HulkMaker** [koehlp/MTA-Mod#1]
why this happen? How can keep all those pedestrians?

**Comment by koehlp** [comment]
This happens because I set the pedestrians from the game to be invisible
(and also collision free). The reason is that they appear and
disappear randomly in the scene and we didn't want to have this recorded.

**Comment by HulkMaker** [comment]
hi Philipp,

Thanks for quick response! 
If all game characters disappeared after recording, so how to generate Pedestrians which can be recording and let them move and behavior?
I have tried use mod function to spawn peds, but neither they can move, nor their can exist after click 'start combine recording'.

BRs,
Charles

**Comment by koehlp** [comment]
They should be spawned by the mod code after you click start combined
recording.

It was some time ago when I ran this. But note that the recording of the
dataset took 3-4 days. The overall gamespeed had to be lowered to ensure a
sufficient framerate.

So it could be the case that it just takes some time until you see the
pedestrians.

But you can also run spawning and walking without recording.

Best regards,

Philipp

HulKing ***@***.***> schrieb am Mo., 7. Juni 2021, 16:42:

**Comment by HulkMaker** [comment]
thanks for explanation. Actually the reason is not this one. I changed the cameras settings with new positions for 6 cameras in another place "Ferris Wheel", but the pedestrians still be spawned in default place(airport), so no one shows in new place.

 Were all spawned pedestrians' walking positions pre-defined in some place? How to quickly defined such kind positions file?  

BRs,
Charles

**Comment by koehlp** [comment]
Yes you can set them in the game too. You have to create a walking graph.
And you can define start / end points where they will spawn or disappear.

HulKing ***@***.***> schrieb am Mi., 9. Juni 2021, 16:49:

**Comment by HulkMaker** [comment]
I didn't find hardware configuration info in your paper, so I want to know which CPU/GPU you used for recording 3~4 days? 
I just use Alienware game laptop which is Nvidia Geforce GTX 1080 GPU and i7 CPU. Is that better than your hardware or worse?

BRs,
Charles

**Comment by koehlp** [comment]
We used a Nvidia Geforce RTX 2080 TI with 11GB memory. CPU was similar.

HulKing ***@***.***> schrieb am Fr., 11. Juni 2021, 04:14:
